feat: support the horizontal layout of MenuBar
DTStack/molecule pull request #553
Opened 2021-12-16 08:21 UTC by kiwiwong

## Description

MenuBar 支持 horizontal 布局

Fixes #457  

## Changes

- Menu 组件改为使用 forwardRef 进行包装
- 修改 MenuBarController 使其支持修改 MenuBar 的布局模式
- layout.ts 中新增 IMenuBarViewState 接口，给menuBar增加了 mode 属性
- const.ts 中增加 menuBar mode 相关常量
- layoutService.ts 中增加 menuBar mode 的 get/set 方法
- 修改 workbench.tsx 布局以支持 horizontal 模式下的 menuBar
- 修改 menuBar 组件以支持 horizontal 模式
- 增加 menuBar horizongtal 模式下样式代码

2021-12-16 08:42 UTC, wewoor reviewed
单元测试需要补一下

2021-12-16 08:54 UTC, mortalYoung requested changes

2021-12-16 08:54 UTC, mortalYoung commented on src/workbench/menuBar/style.scss
> +            background-color: auto !important;
不建议用 !important 看看有没有其他办法提升优先级

2021-12-16 08:54 UTC, mortalYoung commented on src/workbench/menuBar/menuBar.tsx
> +                <Logo className={logoClassName} />
这个 logo 是不是没办法修改了 如果改成 horizontal 的话

2021-12-19 05:23 UTC, wewoor requested changes

2021-12-19 05:23 UTC, wewoor commented on src/controller/menuBar.ts
> +            data.data = newData;
`filterMenuBarDataByIds` 函数我们还是遵循 **immutable** 的原则，考虑返回一个新的**数据对象**，而不是直接**修改参数**中的数据

2021-12-19 05:23 UTC, wewoor commented on src/controller/menuBar.ts
> +            const menuBarData = this.getFilteredMenuBarData(
这段代码跟下面的 `updateMenuBarMode` 重合度很高啊

2021-12-19 05:23 UTC, wewoor commented on src/services/workbench/layoutService.ts
> +     * Set the mode of the menu bar, default is `vertical`
```suggestion
     * Set the mode of the MenuBar, default is `vertical`
```

2021-12-19 05:23 UTC, wewoor commented on src/services/workbench/layoutService.ts
> +     * Get the mode of the menu bar
```suggestion
     * Get the mode of the MenuBar
```

MenuBar 作为我们独立的组件命名，这样跟文档应该更好衔接

2021-12-19 05:23 UTC, wewoor commented on src/workbench/menuBar/menuBar.tsx
> +        icon,
这个 `icon` 是用来自定义 Logo 的吗？如果是，这个名称抽象不够直观。例如 `MenuBar` 组件的 `icon` 属性，其实 这个 `icon` 指的自定义哪个部分，不太好理解，如果是针对 `MenuBar` `horizontal` 模式，索性 `logo` 这个 抽象更好理解些。

接口示例：

```ts
interface IMenuBar {
     icon?: ReactNode;
}
```

```ts
// Better
interface IMenuBar {
     logo?: ReactNode;
}
```

2021-12-20 06:27 UTC, wewoor approved these changes
+1

2021-12-20 06:41 UTC, merged