fix: language pack code unification
DTStack/molecule pull request #558
Opened 2021-12-21 06:24 UTC by SQLGate

## Description

Added Korean language pack.
Also, we have organized the Simplified Chinese and English language packs consistently.

2021-12-21 06:37 UTC, wewoor commented
@SQLGate Are you a Korean developer?   We are glad to see the PR to Molecule, we are going to merge after review.

2021-12-21 06:44 UTC, wewoor requested changes

2021-12-21 06:44 UTC, wewoor commented on src/extensions/locales-defaults/locales/en.json
> +        "sidebar.explore.title": "Explore",
```suggestion
        "sidebar.explore.title": "Explorer",
```
Keep the same abstraction with VS Code.

2021-12-21 06:52 UTC, SQLGate commented on src/extensions/locales-defaults/locales/en.json
> +        "sidebar.explore.title": "Explore",
Good!. My mistake.

2021-12-21 06:58 UTC, SQLGate commented
> @SQLGate Are you a Korean developer? We are glad to see the PR to Molecule, we are going to merge after review.

Yes! I am Korean developer and Delphi developer. This project is the one I've been looking for.
I'm making a database solution called SQLGate
http://www.sqlgate.com
and trying to get this product to work on the web.
So I was looking for an IDE JavaScript framework and I was grateful to see this source.

2021-12-21 08:16 UTC, wewoor approved these changes
+1

2021-12-21 08:27 UTC, wewoor commented
@SQLGate Unit tests failed, there need you to update the snapshots.

2021-12-21 21:47 UTC, SQLGate commented
> @SQLGate Unit tests failed, there need you to update the snapshots.
I will Unit tests, Again check code

2021-12-22 02:06 UTC, wewoor commented
> > @SQLGate Unit tests failed, there need you to update the snapshots.
> > I will Unit tests, Again check code

If you have any questions,  we also can communicate on Discord: https://discord.com/invite/b62gpHwNA7

2021-12-22 05:02 UTC, SQLGate commented
> 

How can i unit test it?

2021-12-22 05:06 UTC, wewoor commented
> > 
> 
> How can i unit test it?

At the root folder, run `yarn test` command

2021-12-23 02:44 UTC, wewoor commented
@SQLGate Maybe we need to extract the locales into an isolated package in the future.

2021-12-23 02:46 UTC, merged