WIP: docs: translate the docs in English
DTStack/molecule pull request #581
Opened 2021-12-29 13:03 UTC by kiwiwong

## Description

Translate the docs in English

Fixes #546

2021-12-30 05:55 UTC, wewoor commented
@SQLGate We are translating the Docs in this iteration #542, would you want to help us to review~

2021-12-30 08:18 UTC, mortalYoung requested changes

2021-12-30 08:18 UTC, mortalYoung commented on website/docs/guides/extend-builtin-ui.md
> +[Problems](../api/interfaces/molecule.IProblemsService) can be used to show some **problems** in the workspace, such as **syntax errors**, **parameter problems**, etc. Like [Output](#output), it is a
这里需要和原本的 markdown 结构保持统一

2021-12-30 08:18 UTC, mortalYoung commented on website/docs/advanced/customize-workbench.md
> +At present, **MenuBar** has a built-in **top layout** function. We will use the **right sidebar (RightSideBar)** as a **built-in** function of Molecule in future versions.
```suggestion
At present, the top fixed layout for the **MenuBar** is integrated in Molecule. Besides, we will also integrate the **right sidebar (RightSideBar)** for Molecule in the future.
```

2021-12-30 08:18 UTC, mortalYoung commented on website/docs/advanced/customize-workbench.md
> +In addition to some built-in atomic [Components](../api/namespaces/molecule.component), Molecule also provides basic **Workbench,SideBar, Editor, ActivityBar, MenuBar, Panel, StatusBar** and other co
突然发现是不是都少了 mardown 的 list 结构 0.0

2021-12-30 08:18 UTC, mortalYoung commented on website/docs/advanced/customize-workbench.md
> +First, we open the [source](https://github.com/DTStack/molecule) code repository of Molecule, find the `src/workbench` directory, then copy the `workbench.tsx` file to the `views` or other directorie
```suggestion
First, we open the [source code](https://github.com/DTStack/molecule) of Molecule, and find the `src/workbench` directory, then copy the `workbench.tsx` file to the `views` or other directories of your project, and rename it to `myWorkbench.tsx`:
```

2021-12-31 04:52 UTC, SQLGate reviewed
I wonder if the PR was requested after translating part of the document rather than translating the entire document.

2022-01-01 06:02 UTC, SQLGate approved these changes

2022-01-04 08:40 UTC, mortalYoung requested changes

2022-01-04 08:40 UTC, mortalYoung commented on website/docs/guides/extend-builtin-ui.md
>  监听**搜索输入控件**的输入内容：
这里忘记删了

2022-01-04 08:40 UTC, mortalYoung commented on website/docs/guides/extend-color-theme.md
> +After the download is complete, we can see:
```suggestion
After the download is completed, we can see:
```

2022-01-04 08:40 UTC, mortalYoung commented on website/docs/guides/extend-color-theme.md
>  然后，我们再创建一个 `themes/MyTheme.json` 文件，具体内容如下：
这句话没翻吗 0.0

2022-01-04 08:40 UTC, mortalYoung commented on website/docs/guides/extension.md
> +### class object
```suggestion
### Class object
```

2022-01-04 08:40 UTC, mortalYoung commented on website/docs/quick-start.md
> +> -   node.js version: **Node.js 12.13.0 +**
```suggestion
> -   Node.js version: **Node.js 12.13.0 +**
```

2022-01-04 09:20 UTC, wewoor requested changes
开头大写：
![image](https://user-images.githubusercontent.com/2766811/148036326-444294a1-99cd-4801-b580-6767426cc4e6.png)

缺空格
![image](https://user-images.githubusercontent.com/2766811/148036828-9660e606-9de2-4b8c-936e-149cb75f93be.png)

2022-01-05 02:32 UTC, mortalYoung approved these changes
+1

2022-01-05 02:32 UTC, wewoor approved these changes
+1

2022-01-05 02:32 UTC, merged