fix: folderTree sort
DTStack/molecule pull request #614
Opened 2022-01-11 13:05 UTC by kiwiwong

## Description

FolderTree's sorting function changed to configurable.

Fixes #582 

## Changes

-   Add the autoSort property, and the default value is false.

2022-01-12 02:11 UTC, wewoor requested changes
另外，FolderTree 排序的，之前是个默认特性，现在可选的设计，还是有必要解释下的。
https://dtstack.github.io/molecule/docs/guides/extend-builtin-ui#foldertree

2022-01-12 02:11 UTC, wewoor commented on src/services/workbench/explorer/folderTreeService.ts
> +    /**
这个 API 的注释可以再详细些

2022-01-12 03:19 UTC, kiwiwong commented
> 另外，FolderTree 排序的，之前是个默认特性，现在可选的设计，还是有必要解释下的。 https://dtstack.github.io/molecule/docs/guides/extend-builtin-ui#foldertree

已在next版本文档中添加了说明

2022-01-13 02:19 UTC, mortalYoung approved these changes
+1

2022-01-13 02:20 UTC, wewoor approved these changes
+1

2022-01-13 02:20 UTC, merged