fix: Connect component supports to unsubscribe event by pass the callback
DTStack/molecule pull request #635
Opened 2022-01-19 12:43 UTC by wewoor

## Description
修复 `connect` Service 多次后，组件销毁后，导致事件无效的问题

Fixes #596  

## Changes
-   `EventEmitter` 支持通过事件 `name` 和 `callback` 函数引用取消订阅
-   `connect` **HOC** 组件，按 `callback` 取消事件订阅

## How Has This Been Tested?

-   [ ] 增加 connect 组件测试用例
-   [ ] 增加 EventEmitter 测试用例
-   [ ] 在 Panel 增加 connect 的测试场景

2022-01-19 15:25 UTC, mortalYoung requested changes

2022-01-19 15:25 UTC, mortalYoung commented on src/react/component.ts
> +    removeOnUpdateState(callback?: Function): void;
calllback 的命名是不是有点歧义，感觉像是异步函数执行完毕之后执行该函数的意思 0.0

2022-01-20 01:59 UTC, wewoor commented on src/react/component.ts
> +    removeOnUpdateState(callback?: Function): void;
是的，我重命名下吧， `listener` 应该更直观

2022-01-20 02:10 UTC, kiwiwong reviewed
+1

2022-01-20 12:44 UTC, mortalYoung approved these changes
+1

2022-01-20 12:45 UTC, merged