support to set the expanded panels of Explorer
DTStack/molecule pull request #753
Opened 2022-05-26 04:06 UTC by mumiao

## Description

support to set the expanded panels of Explorer

Fixes #726 

## Changes

Please describe the changes, help the reviewer to read your code.

-   support to set the expanded panels of Explorer
-   Collapse component support expand activeKeys
-   add  Explorer setExpandedPanels testcase
-   add  Collapse component activePanelKeys attribute testcase

## Checklist

-   [x ] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules

2022-05-27 15:42 UTC, mortalYoung requested changes

2022-05-27 15:42 UTC, mortalYoung commented on src/components/collapse/index.tsx
> +    const useCampare = (value: UniqueId[], compare: Function) => {
自定义的 hook 放到函数体的外面呗

2022-05-27 15:42 UTC, mortalYoung commented on src/services/workbench/explorer/explorerService.ts
> +    setExpandedPanels(activePanelKeys: UniqueId[]): void;
services 的方法记得注释

2022-05-27 15:42 UTC, mortalYoung commented on src/components/collapse/index.tsx
> +    }, [compareActivePanelKeys]);
这一段没太看懂，直接把 controlActivePanelKeys 丢到 deps 里然后 set 不阔以吗 0.0

2022-05-28 14:21 UTC, mumiao commented on src/components/collapse/index.tsx
> +    }, [compareActivePanelKeys]);
不可以, controlActivePanelKeys 是引用对象, 导致 render loop 了

2022-06-02 02:10 UTC, mortalYoung approved these changes
+1

2022-06-02 02:15 UTC, wewoor approved these changes
+1

2022-06-02 02:15 UTC, merged