refactor: refactor Split component
DTStack/molecule pull request #763
Opened 2022-06-14 13:32 UTC by yyllff

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Changes

Please describe the changes, help the reviewer to read your code.

-   Change A
-   Change B

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

-   [ ] Test A
-   [ ] Test B

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

2022-06-14 13:58 UTC, wewoor commented
@yyllff  PR 非常棒，然后描述稍微写一下， 新代码的单测、静态检查需要看看。我们尽快 Review

2022-06-16 02:03 UTC, wewoor requested changes

2022-06-16 02:03 UTC, wewoor commented on src/components/split/sash.tsx
> +    ...others
```suggestion
    ...restProps
```

2022-06-16 02:03 UTC, wewoor commented on src/components/split/sash.tsx
> +            {...others}
```suggestion
            {... restProps}
```

2022-06-16 02:24 UTC, wewoor commented
![image](https://user-images.githubusercontent.com/2766811/173977694-7d4c84e4-a4da-49af-9905-72d935f16991.png)

`Explorer` 这个功能设计应该是默认不能 **Resize** 的 @yyllff

2022-06-16 02:41 UTC, mortalYoung requested changes

2022-06-16 02:41 UTC, mortalYoung commented on src/components/collapse/index.tsx
> +    const handleChangeCallback = (key: React.Key, index) => {
这个 Key 的类型应该是 `UniqueId`

2022-06-16 02:41 UTC, mortalYoung commented on src/components/collapse/index.tsx
> +        if (currentKeys[index]) {
这里可能需要规避当 panel.id 是 0 的情况

2022-06-16 02:41 UTC, mortalYoung commented on src/components/collapse/index.tsx
>          setActivePanelKeys(currentKeys.concat());
如果把 activePanelKeys 的结构改成 `[empty]` 酱紫的结构的话， 我建议 147 行的判断逻辑改一下。虽然结果是保持一致，但是本意上来说是期望当 collapse 有展开项的时候再走 if 分支，否则走 else 分支。 同样需要规避一下 panel.id 是 0 的情况

2022-06-16 07:08 UTC, yyllff commented
> ![image](https://user-images.githubusercontent.com/2766811/173977694-7d4c84e4-a4da-49af-9905-72d935f16991.png)
> 
> `Explorer` 这个功能设计应该是默认不能 **Resize** 的 @yyllff

收到 已修复 麻烦再看下哈

2022-06-16 07:09 UTC, yyllff commented on src/components/collapse/index.tsx
> +        if (currentKeys[index]) {
好的

2022-06-16 07:09 UTC, yyllff commented on src/components/collapse/index.tsx
>          setActivePanelKeys(currentKeys.concat());
好的 已调整

2022-06-16 07:10 UTC, yyllff commented on src/components/collapse/index.tsx
> +    const handleChangeCallback = (key: React.Key, index) => {
好的

2022-06-16 07:59 UTC, mortalYoung requested changes

2022-06-16 07:59 UTC, mortalYoung commented on src/components/collapse/index.tsx
> +            const nextSash: boolean[] = [];
我觉得这一段和 showSashs 的代码可以提取到 useEffect 里，做为 sizes 修改的副作用。可以理解为，如果 sizes 变动了，那么其副作用就是引起 showSashs 的变动。另外，我看 showSashs 这个变量好像没怎么用到，是不是可以用 useMemo 去做

2022-06-16 07:59 UTC, mortalYoung commented on src/components/collapse/index.tsx
> +                        !isUndefined(activePanelKeys[i])
这里可不可以提个变量出来或者两个变量，后续好维护

2022-06-16 07:59 UTC, mortalYoung commented on src/components/split/sash.tsx
> +    const handleMouseMove = function (e) {
这个函数是不是要包一个 useCallback，否则 remove 的时候和 add 的时候已经不是同一个引用地址，handleMouseUp 同理

2022-06-16 07:59 UTC, mortalYoung commented on src/components/split/sash.tsx
> +                timeout.current = setTimeout(() => {
不太清楚会不会存在触发了 onMouseEnter 但是没触发 onMouseLeave 然后组件被卸载掉的情况。不过为了保险起见，你觉得需不需要加一个 useEffect 在 return 里面把定时器清空一下

2022-06-16 07:59 UTC, mortalYoung commented on src/components/collapse/index.tsx
> +            const nextSash: boolean[] = [];
这样做的目的是让 performSizes 函数只负责 sizes 的变更

2022-06-16 09:16 UTC, yyllff commented on src/components/collapse/index.tsx
> +            const nextSash: boolean[] = [];
这块儿我感觉你说的很有道理，setShowSashes其实是没必要的，包括allowResize都是通过activePanelKeys来确定的，完全可以通过useMemo控制

2022-06-16 09:17 UTC, yyllff commented on src/components/collapse/index.tsx
> +                        !isUndefined(activePanelKeys[i])
这个也赞同，提出变量代码可读性变强了，不然很难判断语义

2022-06-16 10:10 UTC, yyllff commented on src/components/split/sash.tsx
> +    const handleMouseMove = function (e) {
这确实是个问题，不过感觉useCallback并木有起到什么作用，useCallback的依赖改变时函数还会重新生成，我把这两个函数放到onMouseDown事件中定义，肯定能够保证remove的和add的是同一个。其实我对useCallback的优化性能一直存疑，js创建一个函数的开销和创建一个变量几乎一样，在实际业务中用了和没用貌似也没体现出性能的差异。

2022-06-16 10:11 UTC, yyllff commented on src/components/split/sash.tsx
> +                timeout.current = setTimeout(() => {
这个操作感觉很严谨

2022-06-17 03:50 UTC, wewoor approved these changes
+1

2022-06-17 05:40 UTC, merged

2022-06-17 06:04 UTC, mumiao commented
+1

2022-10-11 08:51 UTC, yyllff commented
好哒 明儿有时间我看一下 辛苦啦



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月14日 21:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [DTStack/molecule] refactor: refactor Split component (PR #763) |

@yyllff PR 非常棒，然后描述稍微写一下， 新代码的单测、静态检查需要看看。我们尽快 Review

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>