Feat/editor 2.x dilu
DTStack/molecule pull request #861
Opened 2023-10-31 07:31 UTC by OnlyFlyer

## Description

### feature

 - transfer 1.x Editor feature
 - modified moveTab UI

### bugfix

 - set tab modified is true when Editor is changed（dirty file）

## Changes

- transfer  Editor logic includes onCloseOther、onCloseToLeft、onCloseToRight、onCloseAll etc... logic
- add dirty file flag logic
- modified onMoveTab logic& UI，add onMoveTabOver Event

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

-   [ ] Test A
-   [ ] Test B

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

2023-10-31 08:31 UTC, OnlyFlyer commented
### feature

-  迁移 1.x Editor 功能
- 修改拖拽 tab 的交互（参考的 vscode）

### bugfix

- 但编辑 Editor 时，设置 tab modified 为 true

## Changes

- 迁移 Editor 1.x 的功能，包括 onCloseOther、onCloseToLeft 等，统一放到 extension 中管理
- 新增脏文件夹标识的逻辑
- 修改 拖拽tab 的交互，增加 onMoveTabOver 事件

2023-11-01 09:33 UTC, mortalYoung requested changes

2023-11-01 09:33 UTC, mortalYoung commented on src/client/slots/group/index.tsx
> +    onMoveTabOver?: (params: { tabs?: IEditorTab<any>[]; groupId?: UniqueId, tabId?: UniqueId; coveredTabInMove?: UniqueId }) => void;
这两个函数的名字可以取得更好理解一点，可以参考 HTML 的 event 的事件，然后重复的类型可以直接放 types 里去

2023-11-01 09:33 UTC, mortalYoung commented on src/client/slots/group/index.tsx
> +            <DndProvider backend={HTML5Backend} context={window}>
看起来貌似不支持跨 Group 的拖拽，可以支持一下跨 Group 的拖拽

2023-11-01 09:33 UTC, mortalYoung commented on src/const/theme.ts
> +        this.registerColor('tab.coveredBackground', { dark: '#53595D80', light: '#2677CB2E', hcDark: null, hcLight: null });
这个颜色的值参考一下 [VSCode themeColor](https://code.visualstudio.com/api/references/theme-color#side-bar)

2023-11-01 09:33 UTC, mortalYoung commented on src/extensions/editor/index.ts
> +            molecule.editor.updateGroup(groupId!, {
可以把大部分拖拽的逻辑放到 services 里去，然后监听到事件之后直接调比较好。

2023-11-01 09:33 UTC, mortalYoung commented on src/models/editor.ts
> +    public MAX_WAIT_MS_COVERED_TAB = 1000;
暂时先写死好了，等后面 setting 开发差不多了，可以允许用户在 setting 里设置。

2023-11-01 09:33 UTC, mortalYoung commented on src/extensions/editor/index.ts
> +            molecule.editor.updateGroup(groupId!, { ...extraProps });
我理解其实可以直接通过 `molecule.editor.setAcitve(tabId, groupId)` 来设置当前选中就好

2023-11-01 09:33 UTC, mortalYoung commented on src/models/editor.ts
> +        public lastUpdateTime?: number
我感觉这两个值应该是没有必要存下来的

2023-11-01 09:33 UTC, mortalYoung commented on src/services/editor.ts
> +    public onMoveTab(callback: (params: { tabs?: IEditorTab<any>[]; groupId?: UniqueId, tabId?: UniqueId, coveredTabInMove?: UniqueId }) => void) {
subscriptions 统一放在 `L528` 后面吧

2023-11-01 09:33 UTC, mortalYoung commented on website/versioned_docs/version-0.9.0-beta.2/api/classes/molecule.BuiltinService.md
website 下的先不用动

2023-11-07 07:42 UTC, OnlyFlyer commented on website/versioned_docs/version-0.9.0-beta.2/api/classes/molecule.BuiltinService.md
仅修改了名称，`EDITOR_MENU_SPLIT` -> `EDITOR_MENU_SPILIT`

2023-11-10 05:58 UTC, mortalYoung requested changes

2023-11-10 05:58 UTC, mortalYoung commented on src/services/editor.ts
> +            const tab: any = this.getTabById(from.tabId, from.groupId);
这里最好避免用 any 类型吧

2023-11-10 05:58 UTC, mortalYoung commented on src/services/editor.ts
> +    public changeTab(value: string, ev: editor.IModelContentChangedEvent, extraProps: { tabId?: UniqueId | undefined; groupId?: UniqueId | undefined; }): void {
这个方法和 updateTab 方法是不是行为类似，可以统一成一个方法吗？

2023-11-10 06:14 UTC, OnlyFlyer commented on src/services/editor.ts
> +    drag(params: IDragProps): void;
`drag` 可以调整为 `moveTab`，后续命名参考：https://github.com/DTStack/molecule/blob/main/CONTRIBUTING.md#naming

2023-11-14 02:56 UTC, mortalYoung approved these changes
+1

2023-11-14 02:57 UTC, merged