WIP: feat: search
DTStack/molecule pull request #872
Opened 2023-11-27 02:10 UTC by liuxy0551

## 描述

新增 Search 组件

## 变更

Search 相关文件

## 初步效果

![2023-11-27 10 08 05](https://github.com/DTStack/molecule/assets/34759874/5aacf4b9-624a-497c-8dea-a089c4294f7d)

2023-12-01 10:51 UTC, mortalYoung requested changes

2023-12-01 10:51 UTC, mortalYoung commented on src/models/search.ts
> +        value = '',
这里参考一下其他 Model 的风格吧

2023-12-01 10:51 UTC, mortalYoung commented on src/controllers/search.tsx
> +    setValue?: (value?: string) => void;
controller 里不应该有 set 的方法，讲道理应该都是 on 事件

2023-12-01 10:51 UTC, mortalYoung commented on src/client/slots/search/index.tsx
> +    onSearch?: (value: string) => void;
可以基于 search controller 的类型做一些类型体操

2023-12-01 10:51 UTC, mortalYoung commented on src/client/components/input/index.tsx
> +    const inputRef = useRef<HTMLInputElement>(null);
这个 ref 声明出来的作用是？

2023-12-01 10:51 UTC, mortalYoung commented on src/client/components/input/index.tsx
> +            <input
不用 textarea 的话能实现换行么？

2023-12-01 15:00 UTC, liuxy0551 commented on src/client/slots/search/index.tsx
> +    onSearch?: (value: string) => void;
done

2023-12-05 12:34 UTC, mortalYoung requested changes

2023-12-05 12:34 UTC, mortalYoung commented on src/client/components/searchToolbarIcon/index.tsx
> +    const resultIsTree =
要不把这个状态单独抽到 Model 里去

2023-12-05 12:34 UTC, mortalYoung commented on src/controllers/search.ts
> +                    render: (data: IMenuItemProps) => React.createElement(SearchToolbarIcon, { ...data, onClick: this.onToolbarClick } ),
看看能不能不需要自定义 render 直接通过 update toolbar‘s disabled 状态来达到想要的效果

2023-12-06 09:02 UTC, mortalYoung approved these changes
+1

2023-12-06 09:09 UTC, merged