feat: migrate AuxiliaryBar & AuxiliaryBarTab
DTStack/molecule pull request #884
Opened 2024-06-03 10:00 UTC by shiqiWang0

## Description

migrate auxiliaryBar && create auxiliaryBarTab from 1.x

## Fixes # (issue)

## Changes

Please describe the changes, help the reviewer to read your code.

-   Change A
-   Change B

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

2024-06-04 02:38 UTC, mortalYoung requested changes

2024-06-04 02:38 UTC, mortalYoung commented on src/extensions/auxiliaryBar/index.ts
> +            molecule.auxiliaryBar.add({
内置的 extensions 里不加数据

2024-06-04 02:38 UTC, mortalYoung commented on src/client/slots/workbench/index.tsx
> +                <Display visible>{AuxiliaryBarTab}</Display>
AuxiliaryBar 的 visible 的条件应该取决于是否有数据

2024-06-04 02:38 UTC, mortalYoung commented on src/services/layout.ts
> +                this.menuBar.toggleChecked(this.builtin.getState().constants.MENUBAR_ITEM_PANEL); // 控制台 menuBar 是否展示panel的check勾选
这里的注释没啥用

2024-06-04 02:38 UTC, mortalYoung commented on src/services/module.ts
> +            ['auxiliaryBarTab', import('../client/slots/auxiliaryBar/auxiliaryBarTab')],
这个 modulesMap 的作用其实是为了让 Factory 和 Controller 一一对应，所以期望是把 auxiliaryBar 或 auxiliaryBarTab 的某一个干掉，形成一一对应的情况

2024-06-04 02:52 UTC, shiqiWang0 commented on src/client/slots/workbench/index.tsx
> +                <Display visible>{AuxiliaryBarTab}</Display>
要做成没有数据， AuxiliaryBarTab 也不展示的效果吗？

2024-06-07 09:26 UTC, mortalYoung reviewed
如果直接调用 testPane 里的 addAuxiliary 会导致 workbench 一直重复渲染，定位一下看看是什么问题

2024-06-07 09:26 UTC, mortalYoung commented on src/client/slots/auxiliaryBar/index.scss
>          border-radius: 4px;
给 item 加一个 user-select 吧，多点两下就选中标题了

2024-06-11 06:32 UTC, shiqiWang0 commented
> 如果直接调用 testPane 里的 addAuxiliary 会导致 workbench 一直重复渲染，定位一下看看是什么问题

原因是 useAutoPos 中  
`useEffect(() => {
        setState(convertAutoToAbsolute(pos, size));
    }, [pos, size]);`
原因是：  
`
seAutoPos<HTMLDivElement>(
        auxiliaryBar.current ? [300, 'auto',300] : layout.horizontalSplitPanePos, );`
pos 在打开辅助侧边栏赋值了一个数组，导致不断重复渲染； 同时在打开 auxiliaryTab 的状态下是无法拖动的

修改之后 ，我只引用 layout.splitPanePos 用来渲染
 这样的话： 1.  addAuxiliary 中修改 splitPanePos 的值 2. toggle auxiliaryTab 也需要修改 splitPanePos

2024-06-14 03:47 UTC, mortalYoung approved these changes
+1

2024-06-14 03:48 UTC, merged