Fixed two bugs of split component
DTStack/molecule pull request #890
Opened 2024-06-21 01:28 UTC by slobber

[Fixed main panel height limit bug](https://github.com/DTStack/molecule/commit/5da6c5a0e69a9d3b4a6d50d5f44d4b199257c09d)

[disable panel content selectable when dragging splitters](https://github.com/DTStack/molecule/commit/2d18d9063d9434339db338ac8dcaadcdb86d8b49)

2024-06-24 01:34 UTC, shiqiWang0 commented
请问为什么要去掉 Editor 的高度限制呢

2024-06-25 07:23 UTC, slobber commented
主编辑器本不应该有**最大**限制呀
![image](https://github.com/DTStack/molecule/assets/1853799/043534e5-4a57-445b-a52b-76258e01ac2d)
现在是拖拽一下水平分割条，就直接变这样，然后就再也拖不大了

2024-06-25 08:33 UTC, shiqiWang0 commented
目前的设计是 ：当有 Panel 的展示， Editor 会有最大的拖拽高度限制的。建议限制改为 600 ， 再大就可以将 Panel 关闭就好。

2024-06-26 04:34 UTC, slobber commented
这么设计的理由是什么？如果要保证Panel的大小，应该为Panel设置minSize，Editor部分不应该做限制。在大显示器上不管300/600的限制都是比较影响操作的。

参考[vscode](https://github.com/search?q=repo%3Amicrosoft%2Fvscode+maximumSize&type=code) 的 SplitView，除了在侧边栏使用到的 UserProfileDataView，其他所有Panel都没有设置过 maximunSize 为特定值，如果需要设置也是会设置 minimumSize。

2024-06-26 07:32 UTC, shiqiWang0 commented
问题在于： 
1.  就你提供的 PR 来看，如果单纯将 editor 的 maxSize 去掉，由于我们 Panel 是没有最小限制的， 当 editor 最大化后，是需要联动 menuBar 的状态，否则会引入其他 bug； 如图所示： 
![demo](https://github.com/DTStack/molecule/assets/47959147/68fd7a07-3724-4d61-b9fb-ec9e688a0a48)

2. 根据你提供的 minSize 设置思路， 则需要设置在 Panel 上，这样的话仍无法达到想要在拖拽的情况下将 editor 最大化，目前只提供了关闭 Panel 的操作；
3. 如果想达到 Panel 达到某一个最小阙值，实现自动收起， 目前我们还未支持，后续可以考虑优化掉， 也同时期待你的 PR

2024-06-26 07:44 UTC, mortalYoung requested changes
> 应该为Panel设置minSize

你说的没错，这里按照目前的设计思路来看，最好的方式应该是移除 Editor 的 maxSize，为 Panel 加上 minSize

2024-07-05 04:16 UTC, closed without merging